# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\mac25\\Desktop\\Studia\\fpt_projekt\\app'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.datas += [('applogo.ico', 'D:\\users\\student\\Desktop\\app\\applogo.ico', 'DATA'),
            ('excellogo.png', 'D:\\users\\student\\Desktop\\app\\excellogo.png', 'DATA'),
            ('loading_animation\\frame_00_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_00_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_01_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_01_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_02_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_02_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_03_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_03_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_04_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_04_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_05_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_05_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_06_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_06_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_07_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_07_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_08_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_08_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_09_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_09_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_10_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_10_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_11_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_11_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_12_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_12_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_13_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_13_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_14_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_14_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_15_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_15_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_16_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_16_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_17_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_17_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_18_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_18_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_19_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_19_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_20_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_20_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_21_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_21_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_22_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_22_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_23_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_23_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_24_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_24_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_25_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_25_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_26_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_26_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_27_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_27_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_28_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_28_delay-0.03s.gif', 'DATA'),
            ('loading_animation\\frame_29_delay-0.03s.gif', 'D:\\users\\student\\Desktop\\app\\loading_animation\\frame_29_delay-0.03s.gif', 'DATA')]

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='PMS Data Analysis',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
